# Generated by Django 5.1.1 on 2024-09-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Скидка'),
        ),
    ]
